# Copyright 2026 container-compose project authors.
# Licensed under the Apache License, Version 2.0.

ARG SOURCE_IMAGE
FROM ${SOURCE_IMAGE}
COPY --chmod=0755 compose-volume-initializer-linux-arm64 /.compose-volume-initializer
ENTRYPOINT ["/.compose-volume-initializer"]
