#===----------------------------------------------------------------------===#
# Copyright © 2026 container-compose project authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===----------------------------------------------------------------------===#

sonar.projectKey=stephenlclarke_container-compose2
sonar.organization=stephenlclarke
sonar.host.url=https://sonarcloud.io
sonar.projectName=container-compose
sonar.projectVersion=0.1.0

sonar.sources=Sources,Tools/compose-normalizer
sonar.tests=Tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=.build/**,dist/**,**/.swiftpm/**,**/go.sum,Tools/compose-normalizer/**/*_test.go,Tools/coverage/**
sonar.coverage.exclusions=Package.swift,Tests/**,Sources/ComposePlugin/**,Sources/ComposeCore/ContainerExecLiveAdapter.swift,Sources/ComposeCore/ContainerImageLiveAdapter.swift,Sources/ComposeCore/ContainerLifecycleLiveAdapter.swift,Tools/compose-normalizer/**/*_test.go,Tools/coverage/**
sonar.coverageReportPaths=coverage.xml
sonar.go.coverage.reportPaths=Tools/compose-normalizer/coverage.out
sonar.qualitygate.wait=true
